{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valhafin.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "valhafin.frontend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- if and .Values.monitoring.prometheusAnnotations.enabled .Values.monitoring.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "valhafin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
