{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homepage.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
{{- end }}
